[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py populate_defaults && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --log-file - --access-logfile - --error-logfile - --log-level info"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10